### ISSUE TITLE
Using list fields from Persistent results in "non-id/composite keys not expected here"

### ISSUE THREAD

**Issue by erikd** [prowdsponsor/esqueleto#100]
Not sure if this is related to issue #92 or not. Also tried to debug this myself, but got a bit stuck. 

I added the following test case to `test/Test.hs`:

    it "can update list fields" $
      run $ do
        cclist <- insert $ CcList []
        void $ update $ \p -> do
               set p [ CcListNames =. val ["fred"]]
               where_ (p ^. CcListId ==. val cclist)

and then i run the tests it fails with:

    ErrorCall (non-id/composite keys not expected here)

because `unsafeSqlBinOp` doesn't handle `ERawList` as its third parameter.

Currently stuck with `esqueleto < 2.1.3` in my cabal files due to this.

**Comment by meteficha** [comment]
Those composite keys are more trouble than they're worth, bugs everywhere :(.  I'm looking into this.

**Comment by meteficha** [comment]
And it seems that in the future [they may not use `PersistList` anymore](https://github.com/yesodweb/persistent/blob/5f7d0d61a5b513f6a60415267ec1e7de53b0691c/persistent-template/Database/Persist/TH.hs#L702).

**Comment by meteficha** [comment]
Does d4d876c fix your issues?

**Comment by erikd** [comment]
Will test this first thing next week.

**Comment by erikd** [comment]
Yep, all good! Thanks @meteficha!
