### ISSUE TITLE
generic "order by id"

### ISSUE THREAD

**Issue by jhickner** [prowdsponsor/esqueleto#107]
I have a generic `selectAll` that's used by many types, which looks like this:

```haskell
selectAll 
  :: (PersistEntityBackend a ~ SqlBackend, PersistEntity a, MonadIO m) 
  => SqlPersistT m [(Entity a)]
selectAll = select $ from $ \i -> return i
```

All my tables have an `id`, and I'd like to encode that they should be sorted by `id` by default. Is there any way to add a generic `orderBy [asc "id"]` to this generic query?

**Comment by meteficha** [comment]
Did you try `orderBy [asc (i ^. persistIdField)]` or something along these lines? 
http://hackage.haskell.org/package/persistent-2.2/docs/Database-Persist-Class.html#v:persistIdField

**Comment by jhickner** [comment]
Thank you, that works! I didn't know about `persistIdField`.
