### ISSUE TITLE
sum and avg in postgres generate type-errors

### ISSUE THREAD

**Issue by Drezil** [prowdsponsor/esqueleto#111]
using `sum_` or `avg_` on an Int64-Field yields back a `PersistRational` like `PersistRational (95074 % 1)` instead of an Int64.
Changing the Types in the query to Rational errors with `Couldn't match type ‘GHC.Real.Ratio Integer’ with ‘Int64’`

The query i used was
```
runDB $ E.select $ E.from $ \trans -> do
  E.where_ (trans E.^. TransactionInStock E.>. (E.val 0))
  E.groupBy $ trans E.^. TransactionTypeId
  E.groupBy $ trans E.^. TransactionTypeName
  E.orderBy [E.asc (trans E.^. TransactionTypeName)]
  return (trans E.^. TransactionTypeName
         ,E.sum_ $ trans E.^. TransactionInStock
         ,E.avg_ $ (trans E.^. TransactionPriceCents) E.*. (trans E.^. TransactionInStock))
```
with every field being Int64 and TypeName being Text.

**Comment by meteficha** [comment]
From [PostgreSQL's docs](http://www.postgresql.org/docs/current/static/functions-aggregate.html), `sum()` returns "`numeric` for `bigint` arguments".  `persistent-postgresql` then [converts `numeric` into `PersistentRational`](http://hackage.haskell.org/package/persistent-postgresql-2.2/docs/src/Database-Persist-Postgresql.html#line-337).  So, you need to get the result of `sum_` and `avg_` as a type that accepts conversion from `PersistRational`, such as `Double` or `Rational`.

Regarding the error message, please post the full error message.

**Comment by Drezil** [comment]
Oh. Nevermind. The error that was yielded after changing the resulting types to `Rational` was inside some functtion still expecting Int64 and i have mistaken it for having something to do with the Type of TransactionInStock and the like.

Sorry for the inconvinience.

**Comment by meteficha** [comment]
No problem!
