### ISSUE TITLE
Weird behaviour with Boolean values in where clause

### ISSUE THREAD

**Issue by rubenmoor** [prowdsponsor/esqueleto#112]
Possibly related to [this question on stackoverflow](http://stackoverflow.com/questions/31836740/a-database-esqueleto-riddle-regarding-val-true).

The following query resulted in an empty list, even though I expected values (i.e. my database contains ordinates that have the field `IsScopeFilter` set to `True`):

    runDb . select . from $ (expression `LeftOuterJoin` ordinate) -> do
      on $ ordinate ?. OrdinateFkExpression ==. just (expression ^. ExpressionId)
      where_ $ ordinate ?. OrdinateIsScopeFilter ==. just (val True)
      return (expression, ordinate)

Inspired by a former experience (documented in the stackoverflow question) I changed it to

    runDb . select . from $ (expression `LeftOuterJoin` ordinate) -> do
      on $ ordinate ?. OrdinateFkExpression ==. just (expression ^. ExpressionId)
      where_ $ not_ (ordinate ?. OrdinateIsScopeFilter ==. just (val False))
      return (expression, ordinate)

and it works: I get those ordinates, and only those, which have `IsScopeFilter` set to `True`.

Any ideas what might be going on here?

Edit: I'm working on a Sqlite3 backend.

**Comment by meteficha** [comment]
Looks like a SQLite bug. Can you try to reproduce it using the SQLite REPL?

**Comment by rubenmoor** [comment]
I have to withdraw this issue, until I have tested it further. It might be a different problem altogether, related to [this question](http://stackoverflow.com/questions/32380467/how-to-compose-queries-subselect-with-esqueleto) on stackoverflow.
