### ISSUE TITLE
no From instance for queries with more than 8 tables

### ISSUE THREAD

**Issue by rubenmoor** [prowdsponsor/esqueleto#113]
If I interpret my testing correctly, `From` instances go to a maximum of up to 8 entities. I have a query involving 10 tables. Is there a way to work around this limit w/o doing two queries?

**Comment by meteficha** [comment]
Ah, don't worry about it, I promise you'll probably never hit that limit in practice.  And if you ever do, just use either nested tuples or one of the explicit joins.

**Comment by rubenmoor** [comment]
Alright! Replacing the tuple with `InnerJoin` did the trick for me. I did not design the table where this awful join was necessary ... never underestimate the power of European bureaucracy. They figured out how to do entity relations and now they nest them like there's no tomorrow.

**Comment by meteficha** [comment]
The "in practice" comment was more about being slightly easier to use `InnerJoin` when there are many tables, at least IMHO. :)
