### ISSUE TITLE
insertSelectCount equivalent to updateCount

### ISSUE THREAD

**Issue by bitemyapp** [prowdsponsor/esqueleto#124]
Seems to be missing? Cf. https://hackage.haskell.org/package/esqueleto-2.4.1/docs/Database-Esqueleto.html#v:insertSelect

**Comment by meteficha** [comment]
Should be very straightforward, just refactoring `insertSelect` à la `update`/`updateCount` and adding sanity unit tests.  Do you want to take a stab at it?

**Comment by bitemyapp** [comment]
>Do you want to take a stab at it?

@meteficha charge me with knife crime pls

**Comment by meteficha** [comment]
Fixed by #125.
