### ISSUE TITLE
join on multiple columns (?)

### ISSUE THREAD

**Issue by JohnFirth** [prowdsponsor/esqueleto#126]
Is it possible to write something like the following with Esqueleto? Sorry if I've missed something.

SELECT * 
FROM table1
INNER JOIN table2 
ON table1.column1_name = table2.column1_name
AND table1.column2_name = table2.column2_name;

**Comment by meteficha** [comment]
Yeah, just do something like:

```haskell
select $
from $ \(t1 `InnerJoin` t2) -> do
on $ t1 ^. Table1Column1 ==. t2 ^. Table2Column1 &&.
     t1 ^. Table1Column2 ==. t2 ^. Table2Column2 
return (t1, t2)
```
