### ISSUE TITLE
info: helper functions and common queries

### ISSUE THREAD

**Issue by rubenmoor** [prowdsponsor/esqueleto#127]
I compiled a couple of helper functions and common queries for use together with esqueleto in a personal library.

It can be found here:

https://github.com/rubenmoor/gerippe/blob/master/src/Database/Gerippe.hs

I happen to use those functions frequently and with the use of this library I can reduce custom queries to a minimum. For me it's fine to have them separate. If you see value in having them inside Esqueleto, however, let me know and I'll create a pull request. Any feedback welcome.

**Comment by meteficha** [comment]
My opinion:

* I dislike `keyToId` and friends.

* `getAll` and `getWhere` are interesting, but I don't know how I feel wrt to adding them.

* The `join*` functions make your code a lot less verbose at the cost of making it a lot less readable.  I don't dislike them per se, but I wouldn't want to make them standard.

**Comment by rubenmoor** [comment]
Thanks. Alright then, I'll probably add more of those generic queries as I need them in my code. So if nothing else, it can serve to demonstrate example usage.
