### ISSUE TITLE
SELECT with locking support

### ISSUE THREAD

**Issue by kmandelbaum** [prowdsponsor/esqueleto#39]
Hello!

Can I express a SELECT query with "FOR UPDATE"/"LOCK IN SHARED MODE" options to be able to lock the rows in persistent / esqueleto until the end of transaction? This could be useful.

Thank you.

**Comment by meteficha** [comment]
`esqueleto-2.2.7` has support for simple lock clauses, the ones mentioned here included.

**Comment by kmandelbaum** [comment]
Cool! thanks :)
