### ISSUE TITLE
concat_ with [Value (Maybe Text)]

### ISSUE THREAD

**Issue by tlaitinen** [prowdsponsor/esqueleto#57]
I'd like to concat_ two strings  that may be NULL, but I can't figure out how.

See code snippet at http://lpaste.net/102363

At least in PostgreSQL it is allowed to have NULL values as input for concat-function. NULL-values will be ignored.

**Comment by jhickner** [comment]
I ran into this too and this issue helped. I was trying to use `ilike` to search with in a `Maybe Text` field as defined by persistent. It seems there's no way to do any operation involving strings on a `Maybe` field without this instance. Maybe this should be in the docs somewhere?

**Comment by meteficha** [comment]
It seems there are many possible workarounds:

  1. Put a note on `concat_` and `(++.)` docs saying that you need to write that orphan instance.

  2. Remove the `IsString` constraint (i.e., accept any data type implementing `PersistField`).

  3. Substitute the `IsString` constraint for a new type class, say, `EsqueletoString`, with implementations for `String`, `Text` and `Maybe a`.

Thoughts?

**Comment by meteficha** [comment]
I've released esqueleto-2.4.0 with a new SqlString class of which Maybe is an instance. Also, there's now castString. Please re-open this issue if you feel something is missing :).
