### ISSUE TITLE
Add support for SELECT DISTINCT ON?

### ISSUE THREAD

**Issue by jprider63** [prowdsponsor/esqueleto#72]
Have you considered adding support for SELECT DISTINCT ON? See [here](http://dba.stackexchange.com/questions/49540/how-do-i-efficiently-get-the-most-recent-corresponding-row/49555#49555) for an example.

**Comment by meteficha** [comment]
There is now support for `DISTINCT ON` since `esqueleto-2.2.4`, released a few moments ago.

**Comment by AKurilin** [comment]
Thank you! :D
