### ISSUE TITLE
Nested inner and outer joins

### ISSUE THREAD

**Issue by pacak** [prowdsponsor/esqueleto#8]
Suppose you have following tables a - b - c, where b contains reference to a in a_id, and c contains reference to b in b_id and we want to extract **all rows from a** and those rows from c which are referenced to a via b if any. It's possible with sql code like 

SELECT a.*, bc.* FROM a LEFT OUTER JOIN (b JOIN c ON b.c_id = c.id) bc ON a.id = bc.a_id;

Field names in sqlite will be a bit messed up, but it works. Important part here are parenthesis around inner join.

Following code in esqueleto typechecks fine

from $ \( a `LeftOuterJoin` (b `InnerJoin` c))

but generated sql code contains no parenthesis - since parenthesis provided in the haskell source signify only order of nesting, but not sql nested joins and because of that resulting sql query will contain **only those of a which have non-null refecences to c**.

**Comment by meteficha** [comment]
@pacak, I assume that #97 fixes this issue.  Please re-open it if you feel that we still have work to do :).
