### ISSUE TITLE
esqueleto-2.1.2.1 test suite failure

### ISSUE THREAD

**Issue by peti** [prowdsponsor/esqueleto#93]
The test suite fails as follows in our CI environment: http://hydra.cryp.to/build/658551/log/raw.

**Comment by meteficha** [comment]
Can you still reproduce the test suite failure?  The link isn't working and the test suite works for me using SQLite (the default).  Using PostgreSQL it's currently failing due to persistent's spotty support for custom primary keys.

**Comment by peti** [comment]
@meteficha, the link works again. The server was offline last night due to a power outage, but it's back online and the build log is still there.

**Comment by meteficha** [comment]
Can you still reproduce it?  The test suite runs fine on SQLite for me, so we'll have to dig why your SQLite doesn't behave like mine.

**Comment by peti** [comment]
I've re-run the test suite with `esqueleto-2.2`, and it succeeds in NixOS. I guess this means the error's been fixed, or something. I'll open a new ticket should I encounter this issue again. Thank you for your help!
